#!/bin/sh

# Copyright (c) 2016 Open Baton (http://www.openbaton.org)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


##########################
#### General Settings ####
##########################

set -e
set -u
#set -x # only for DEBUG

# Make available the functions defined in /lib/lsb/init-functions
. /lib/lsb/init-functions


##########################
#### Global Variables ####
##########################

OPENBATON_COMPONENT_NAME_FANCY="ZABBIX Monitoring Plugin"
OPENBATON_COMPONENT_NAME=plugin-monitoring-zabbix

OPENBATON_COMPONENT_BASE_DIR=/usr
OPENBATON_COMPONENT_EXE_DIR=${OPENBATON_COMPONENT_BASE_DIR}/bin

OPENBATON_BASE_CONFIG_DIR="/etc/openbaton"
OPENBATON_COMPONENT_CONFIG_FILE="openbaton-${OPENBATON_COMPONENT_NAME}.properties"

OPENBATON_COMPONENT_AUTOSTART_DEFAULT=true
OPENBATON_COMPONENT_AUTOSTART=${OPENBATON_COMPONENT_AUTOSTART:-$OPENBATON_COMPONENT_AUTOSTART_DEFAULT}

DEBIAN_FRONTEND_DEFAULT=interactive
DEBIAN_FRONTEND=${DEBIAN_FRONTEND:-$DEBIAN_FRONTEND_DEFAULT}

ZABBIX_PLUGIN_IP_DEFAULT=localhost
ZABBIX_SERVER_IP_DEFAULT=localhost
ZABBIX_USER_DEFAULT=Admin
ZABBIX_USER_PASSWORD_DEFAULT=zabbix


####################
#### Open Baton ####
####################

configure_zabbix_server () {
    # In case of "noninteractive" FRONTEND the default value will remain valid (user: admin ; password: openbaton)
    if [ "${DEBIAN_FRONTEND}" != "Noninteractive" -a "${DEBIAN_FRONTEND}" != "noninteractive" ]; then
        read -p " * Please, provide the IP of the Zabbix plugin host [localhost]: " zabbix_plugin_ip

        read -p " * Please, provide the ZABBIX server IP [localhost]: " zabbix_server_ip

        read -p " * Please, provide the ZABBIX user [Admin]: " zabbix_user

        # Turning echo on and off between password reading
        stty -echo
        read -p " * Please, provide the ZABBIX user's password [zabbix]: " zabbix_user_password ; echo
        stty echo
    fi

    # Set the Zabbix Plugin IP
    export zabbix_plugin_ip=${zabbix_plugin_ip:-$ZABBIX_PLUGIN_IP_DEFAULT}
    if [ -z ${zabbix_plugin_ip} ] ; then # The empty string is considered as unset
        sed -i "s|zabbix-plugin-ip\s*=*|zabbix-plugin-ip=${zabbix_plugin_ip}|g" ${OPENBATON_BASE_CONFIG_DIR}/${OPENBATON_COMPONENT_CONFIG_FILE}
    fi

    # Set the zabbix server ip
    export zabbix_server_ip=${zabbix_server_ip}
    if [ -z ${zabbix_server_ip} ] ; then # The empty string is considered as unset
        zabbix_server_ip=${ZABBIX_SERVER_IP_DEFAULT}
    fi
    log_success_msg "Setting the ZABBIX server IP: ${zabbix_server_ip}"
    sed -i "s|zabbix-host\s*=\s*localhost|zabbix-host=${zabbix_server_ip}|g" ${OPENBATON_BASE_CONFIG_DIR}/${OPENBATON_COMPONENT_CONFIG_FILE}

    # Set the zabbix user
    export zabbix_user=${zabbix_user}
    if [ -z ${zabbix_user} ] ; then # The empty string is considered as unset
        zabbix_user=${ZABBIX_USER_DEFAULT}
    fi
    log_success_msg "Setting the ZABBIX user: ${zabbix_user}"
    sed -i "s|user-zbx\s*=\s*admin|user-zbx=${zabbix_user}|g" ${OPENBATON_BASE_CONFIG_DIR}/${OPENBATON_COMPONENT_CONFIG_FILE}

    # Set the zabbix user's password
    export zabbix_user_password=${zabbix_user_password}
    if [ -z ${zabbix_user_password} ] ; then # The empty string is considered as unset
        zabbix_user_password=${ZABBIX_USER_PASSWORD_DEFAULT}
    fi
    log_success_msg "Setting the ZABBIX user's password: ${zabbix_user_password}"
    sed -i "s|password-zbx\s*=\s*zabbix|password-zbx=${zabbix_user_password}|g" ${OPENBATON_BASE_CONFIG_DIR}/${OPENBATON_COMPONENT_CONFIG_FILE}
}

configure () {
    log_success_msg "Configuring Open Baton ${OPENBATON_COMPONENT_NAME_FANCY} installation .."
    configure_zabbix_server
    chmod a+x ${OPENBATON_COMPONENT_EXE_DIR}/openbaton-${OPENBATON_COMPONENT_NAME}
    log_success_msg "Open Baton ${OPENBATON_COMPONENT_NAME_FANCY} installation completed"

    # Allow the use of the .deb package to install the Open Baton Component with Docker (the Docker file developer need to manage the starting of the Component in the Docker file) 
    if [ "${OPENBATON_COMPONENT_AUTOSTART}" = "true" ]; then
        if systemctl start openbaton-${OPENBATON_COMPONENT_NAME}.service >/dev/null 2>&1 ; then
            log_success_msg "Starting the Open Baton ${OPENBATON_COMPONENT_NAME_FANCY} .."
        elif start openbaton-${OPENBATON_COMPONENT_NAME} >/dev/null 2>&1 ; then
            log_success_msg "Starting the Open Baton ${OPENBATON_COMPONENT_NAME_FANCY} .."
        else 
            log_failure_msg "Starting the Open Baton ${OPENBATON_COMPONENT_NAME_FANCY}"
        fi
    fi
}

configure
